/**
 * Clean & Deduplicate Chunks & Chapters Utility
 * 
 * Automatically detects and strips out empty / stub placeholder chapters
 * (like (Empty), [Text missing in source], [Content omitted in source text], (Note: This chapter is empty...))
 * and merges duplicate chapter entries so users get a clean, seamless novel sequence
 * from Chapter 1 to the end without blank or duplicated entries.
 */

// Common anti-leech / stub placeholder text patterns generated by scraper sites or crawler stubs
const STUB_TEXT_PATTERNS = [
  /\[content omitted in source text\]/i,
  /\[text missing in source\]/i,
  /\(empty chapter\)/i,
  /\(empty\)/i,
  /\[empty\]/i,
  /\(note:\s*this chapter is empty[^)]*\)/i,
  /\[this chapter is empty[^\]]*\]/i,
  /\[no content[^\]]*\]/i,
  /\[placeholder\]/i,
  /本章内容缺失/i,
  /此章节为空/i,
  /防盗章节/i,
  /防采集/i,
  /章节内容为空/i,
  /内容加载失败/i,
  /请等待作者更新/i,
  /未完待续，请等待/i,
  /\[content omitted\]/i,
  /\(placeholder chapter\)/i,
  /temporary stub/i,
  /anti-leech placeholder/i,
];

// Common title indicators of empty / stub chapters
const STUB_TITLE_PATTERNS = [
  /\(empty\)/i,
  /\[empty\]/i,
  /（空）/i,
  /【空】/i,
  /\[空\]/i,
  /\(空\)/i,
  /（防采集）/i,
  /【防采集】/i,
  /\(防采集\)/i,
  /\[防采集\]/i,
  /（防盗）/i,
  /【防盗】/i,
  /\(防盗\)/i,
  /\[防盗\]/i,
  /\(stub\)/i,
  /\[stub\]/i,
  /\(placeholder\)/i,
  /\[placeholder\]/i,
  /\(duplicate\)/i,
  /\[duplicate\]/i,
];

/**
 * Checks if a piece of text is purely an empty stub or anti-scraper placeholder
 */
export function isStubOrEmptyText(text?: string): boolean {
  if (!text) return true;
  const trimmed = text.trim();
  if (!trimmed) return true;

  // Check against known explicit stub patterns
  for (const pattern of STUB_TEXT_PATTERNS) {
    if (pattern.test(trimmed)) {
      // If the text is short (< 300 chars) and matches stub pattern, it's definitely a stub
      if (trimmed.length < 300) return true;
    }
  }

  // If text is extremely short (< 80 chars), check if it is just a repeated title, note, or error message
  if (trimmed.length < 80) {
    const lower = trimmed.toLowerCase();
    if (
      lower.includes("empty") ||
      lower.includes("placeholder") ||
      lower.includes("content omitted") ||
      lower.includes("missing in source") ||
      lower.includes("no content") ||
      lower.includes("本章内容缺失") ||
      lower.includes("章节为空") ||
      lower.includes("防采集") ||
      lower.includes("防盗")
    ) {
      return true;
    }
  }

  return false;
}

/**
 * Checks if a chunk / chapter object is an empty stub
 */
export function isStubOrEmptyChunk(chunk: {
  chapterTitle?: string;
  chineseText?: string;
  englishText?: string;
}): boolean {
  if (!chunk) return true;

  const title = chunk.chapterTitle || "";
  const hasStubTitle = STUB_TITLE_PATTERNS.some((pattern) => pattern.test(title));

  const hasNoChinese = !chunk.chineseText || isStubOrEmptyText(chunk.chineseText);
  const hasNoEnglish = !chunk.englishText || isStubOrEmptyText(chunk.englishText);

  // If title explicitly marks it as empty and there's no substantial text
  if (hasStubTitle && (hasNoChinese || hasNoEnglish)) {
    return true;
  }

  // If both Chinese and English texts are empty or stubs
  if (hasNoChinese && hasNoEnglish) {
    return true;
  }

  // If English text exists but is explicitly a stub note
  if (chunk.englishText && isStubOrEmptyText(chunk.englishText)) {
    return true;
  }

  return false;
}

/**
 * Extracts a normalized chapter key for comparison (e.g. "Chapter 2 (Empty)" -> "chapter_2", "第2章" -> "chapter_2")
 */
export function extractChapterNormalizedKey(title?: string, fallbackIndex?: number): string {
  if (!title) return `idx_${fallbackIndex ?? 0}`;
  const cleaned = title
    .replace(/\(empty\)|\(stub\)|\(placeholder\)|\(duplicate\)|\[empty\]|\[stub\]|\[placeholder\]|\[duplicate\]/gi, "")
    .replace(/（空）|【空】|\[空\]|\(空\)|（防采集）|【防采集】|\(防采集\)|\[防采集\]|（防盗）|【防盗】|\(防盗\)|\[防盗\]/g, "")
    .trim();

  // Match English chapter number e.g. "Chapter 2", "Chapter 02"
  const enMatch = cleaned.match(/chapter\s*(\d+)/i);
  if (enMatch) {
    return `chapter_${parseInt(enMatch[1], 10)}`;
  }

  // Match Chinese chapter number e.g. "第2章", "第 2 章", "第二章"
  const zhMatch = cleaned.match(/第\s*([0-9零一二三四五六七八九十百千万]+)\s*[章回节卷集部篇折话]/i);
  if (zhMatch) {
    return `zh_chapter_${zhMatch[1].trim()}`;
  }

  // Match leading number e.g. "2. The Beginning" or "2 "
  const numMatch = cleaned.match(/^(\d+)[\s.:、]/);
  if (numMatch) {
    return `chapter_${parseInt(numMatch[1], 10)}`;
  }

  return cleaned.toLowerCase().replace(/\s+/g, "_");
}

/**
 * Strips out stub / placeholder markers from chapter title (e.g. "Chapter 2 (Empty)" -> "Chapter 2")
 */
export function cleanChapterTitle(title?: string): string {
  if (!title) return "";
  return title
    .replace(/\s*\((?:empty|stub|placeholder|duplicate)\)/gi, "")
    .replace(/\s*\[(?:empty|stub|placeholder|duplicate)\]/gi, "")
    .replace(/\s*[（(]【?空】?[）)]/g, "")
    .replace(/\s*\[【?空】?\]/g, "")
    .replace(/\s*[（(]防(?:采集|盗)[）)]/g, "")
    .replace(/\s*\[防(?:采集|盗)\]/g, "")
    .replace(/\s*【防(?:采集|盗)】/g, "")
    .trim();
}

/**
 * Cleans and deduplicates an array of TextChunks.
 * - Strips empty / stub placeholder chapters
 * - Merges consecutive chunks that belong to the same chapter title
 * - Preserves strict sequential chapter order
 */
export function cleanAndDeduplicateChunks<
  T extends {
    id?: string;
    index: number;
    chapterTitle?: string;
    chineseText?: string;
    englishText?: string;
    charCount?: number;
    wordCount?: number;
    status?: string;
    attempts?: number;
    errorMessage?: string;
  }
>(chunks: T[]): T[] {
  if (!chunks || chunks.length === 0) return [];

  // Sort strictly by chunk index to guarantee uninterrupted narrative order
  const sorted = [...chunks].sort((a, b) => (a.index ?? 0) - (b.index ?? 0));

  const result: T[] = [];

  for (let i = 0; i < sorted.length; i++) {
    const chunk = sorted[i];
    const isStub = isStubOrEmptyChunk(chunk);

    // If this chunk is a stub:
    if (isStub) {
      // Check if adjacent chunk (before or after) is the real version of this same chapter
      const key = extractChapterNormalizedKey(chunk.chapterTitle, chunk.index);
      const nextChunk = sorted[i + 1];
      const prevChunk = result[result.length - 1];

      const nextKey = nextChunk ? extractChapterNormalizedKey(nextChunk.chapterTitle, nextChunk.index) : null;
      const prevKey = prevChunk ? extractChapterNormalizedKey(prevChunk.chapterTitle, prevChunk.index) : null;

      // If next chunk or previous chunk is the real version of this chapter, drop this duplicate empty stub
      if (key && (key === nextKey || key === prevKey)) {
        continue;
      }

      // If the chunk has a distinct chapter title/number not already in result, preserve it with placeholder note
      // so we never delete chapters 37-86 from the table of contents or file export
      const cleanedTitle = cleanChapterTitle(chunk.chapterTitle) || chunk.chapterTitle || `Chapter ${chunk.index}`;
      result.push({
        ...chunk,
        chapterTitle: cleanedTitle,
        englishText: chunk.englishText || "[Content missing or omitted in source website]",
      });
      continue;
    }

    // Clean title of any leftover (Empty) / [Empty] tags
    const cleanedTitle = cleanChapterTitle(chunk.chapterTitle);
    const cleanedChunk = {
      ...chunk,
      chapterTitle: cleanedTitle || chunk.chapterTitle,
    };

    // Check if the previous chunk in result has the exact same normalized chapter key
    const prevInResult = result[result.length - 1];
    if (prevInResult) {
      const currentKey = extractChapterNormalizedKey(cleanedChunk.chapterTitle, cleanedChunk.index);
      const prevKey = extractChapterNormalizedKey(prevInResult.chapterTitle, prevInResult.index);

      if (currentKey && currentKey === prevKey) {
        // Same chapter! Merge them seamlessly
        const mergedChinese = [
          (prevInResult.chineseText || "").trim(),
          (cleanedChunk.chineseText || "").trim(),
        ]
          .filter(Boolean)
          .join("\n\n");

        const mergedEnglish = [
          (prevInResult.englishText || "").trim(),
          (cleanedChunk.englishText || "").trim(),
        ]
          .filter(Boolean)
          .join("\n\n");

        const preferredTitle =
          !prevInResult.chapterTitle?.includes("(") && !prevInResult.chapterTitle?.includes("[")
            ? prevInResult.chapterTitle
            : cleanedChunk.chapterTitle || prevInResult.chapterTitle;

        result[result.length - 1] = {
          ...prevInResult,
          chapterTitle: cleanChapterTitle(preferredTitle),
          chineseText: mergedChinese,
          englishText: mergedEnglish,
          charCount: (prevInResult.charCount || 0) + (cleanedChunk.charCount || 0),
          wordCount: (prevInResult.wordCount || 0) + (cleanedChunk.wordCount || 0),
          status:
            prevInResult.status === "completed" || cleanedChunk.status === "completed"
              ? "completed"
              : prevInResult.status,
        };
        continue;
      }
    }

    result.push(cleanedChunk);
  }

  // Re-normalize indices sequentially 0..N-1 so caller gets a continuous stream
  return result.map((c, idx) => ({
    ...c,
    index: idx,
  }));
}

/**
 * Cleans and deduplicates a chapter list (TOC) for Reader Mode & Navigation
 */
export function cleanAndDeduplicateChapterList(
  chapters: Array<{ title: string; url: string; index?: number }>
): Array<{ title: string; url: string; index: number }> {
  if (!chapters || chapters.length === 0) return [];

  const result: Array<{ title: string; url: string; index: number }> = [];

  for (let i = 0; i < chapters.length; i++) {
    const item = chapters[i];
    const rawTitle = item.title || "";

    const hasStubTitle = STUB_TITLE_PATTERNS.some((p) => p.test(rawTitle));
    const nextItem = chapters[i + 1];
    const prevItem = result[result.length - 1];

    const currentKey = extractChapterNormalizedKey(rawTitle, item.index ?? i + 1);
    const nextKey = nextItem ? extractChapterNormalizedKey(nextItem.title, nextItem.index ?? i + 2) : null;
    const prevKey = prevItem ? extractChapterNormalizedKey(prevItem.title, prevItem.index ?? result.length) : null;

    // If this item is marked as (Empty) / [Empty] and followed or preceded by the real chapter, skip it!
    if (hasStubTitle && (currentKey === nextKey || currentKey === prevKey)) {
      continue;
    }

    // If this item has identical key to the previous item in result, skip duplicate
    if (prevKey && currentKey === prevKey) {
      continue;
    }

    result.push({
      ...item,
      title: cleanChapterTitle(rawTitle),
      index: result.length + 1,
    });
  }

  return result;
}

/**
 * Checks if two novel titles refer to the same novel, accounting for:
 * - .txt / .epub / .pdf / .json extensions
 * - Chapter range suffixes like _Ch1_to_50, _ch1-100, -1-50
 * - Bracket markers like 【...】 or [...]
 * - Punctuation, casing, and whitespace normalization
 * - Substring containment (e.g. base title vs full chapter filename)
 */
export const KNOWN_NOVEL_ALIASES: Array<[string, string]> = [
  ["primitive chen qi", "穿越兽世当神棍"],
  ["primitivechenqi", "穿越兽世当神棍"],
  ["chen qi", "穿越兽世当神棍"],
  ["chenqi", "穿越兽世当神棍"],
  ["chuanyueshoshidangshengun", "primitive chen qi"],
  ["raising cubs and building a tribe in the beast world", "在兽世养崽建部落"],
  ["modern bird parrot bai linlin", "现代小鸟白林林"],
  ["yiren bei rebellion", "一人之下"],
];

export function isSameNovel(name1?: string, name2?: string): boolean {
  if (!name1 || !name2) return false;
  const norm = (s: string) =>
    s
      .replace(/\.(txt|epub|pdf|json)$/i, "")
      .toLowerCase()
      .replace(/[_ -]ch(?:apter)?\s*\d+.*$/i, "")
      .replace(/\[.*?\]/g, "")
      .replace(/【.*?】/g, "")
      .replace(/[^a-z0-9\u4e00-\u9fa5]/g, "");
  const n1 = norm(name1);
  const n2 = norm(name2);
  if (!n1 || !n2) return false;
  if (n1 === n2 || n1.includes(n2) || n2.includes(n1)) return true;

  for (const [aliasA, aliasB] of KNOWN_NOVEL_ALIASES) {
    const normA = norm(aliasA);
    const normB = norm(aliasB);
    if (
      (n1.includes(normA) && n2.includes(normB)) ||
      (n2.includes(normA) && n1.includes(normB)) ||
      (n1.includes(normB) && n2.includes(normA)) ||
      (n2.includes(normB) && n1.includes(normA))
    ) {
      return true;
    }
  }
  return false;
}
